version: 2.1
jobs:
  build:
    docker:
      - image: rastasheep/ubuntu-sshd
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7f:b7:54:67:2e:ca:87:39:72:30:29:47:06:bb:96:a5"
      - checkout
      - run:
          name: Running Update
          command: |
            ssh -o StrictHostKeyChecking=no ppsree@ppsree.net 'cd chat-app && git pull && make restart'
      # - run:
      #     name: Pulling Latest build for nginx from Git Repo
      #     command: |
      #       cd nginx-server
      #       git pull
      # - run: 
      #     name: Restarting nginx server
      #     command: |
      #       make stop
      #       make start